### ISSUE TITLE
feature extraction check point

### ISSUE THREAD

**Issue by chychiang** [chychiang/tmod#1]
## What to do

To do this part, collect a dataset and and then extract features from this dataset using at least 3 substantially different feature extraction methods discussed in class. For example, LDA and Kernel LDA are considered similar to each other, PCA, Kernel PCA and LSA are considered similar, k-Means and Gaussian clustering are considered similar. Of the 3 methods, at least one of them should be used to show us a visualization of the dataset, and at least one of them should be used for subsequent regression or classification. For image/video/audio/text applications, at least one method must be a Manual feature extraction method. You can use a feature extraction method you have read about in a publication, if that is more suited to your application. If you spend significant effort in collecting data (such as making measurements yourself, say using a cell phone, instead of simply downloading data), you only need show us one feature extraction method.

## What to submit

- [x] A small sample of your dataset. This can be a zip file or a text, csv or excel file.
- [x]  Any software code you have developed for Feature extraction. This can be a zip file or a Matlab file or Python notebook.
- [x] A picture showing visualization of features extracted from your dataset, as specified below. This must be a single image, pdf or word file. Do not upload a zip file for this part.

## Todos

- [x] collect data: record videos of objects in a scene
- [x] develop code for one manual feature extraction method
- [x] develop code for one automatic feature extraction method
- [x] visualize extracted features for presentation (use the same slides for thie entire project - submit just the feature extraction section)
